on: push #Evento em que sera disparado o workflow

jobs: #Onde criamos as Jobs
    job1-hello:
        runs-on: ubuntu-latest
        steps: #Etapas dentro da job
        - name: Imprimir mensagem
          run: echo "Olá, Mundo"
    job2-goodbye:
        runs-on: ubuntu-latest #onde vai rodar o workflow
        steps:
        - name: Step 1 - Sequencia de instruções
          run: |
            echo "Uma nova instrução"
            ls
        - name: Step 2 - Imprimir mensagem
          run: echo "Até logo!"